export { default as AllUsers } from "@/_root/pages/AllUsers";
export { default as CreatePost } from "@/_root/pages/CreatePost";
export { default as EditPost } from "@/_root/pages/EditPost";
export { default as Explore } from "@/_root/pages/Explore";
export { default as Home } from "@/_root/pages/Home";
export { default as PostDetails } from "@/_root/pages/PostDetails";
export { default as Profile } from "@/_root/pages/Profile";
export { default as Saved } from "@/_root/pages/Saved";
export { default as UpdateProfile } from "@/_root/pages/UpdateProfile";
